services:
  postgres:
    image: postgres:15
    container_name: backlog-postgres
    environment:
      POSTGRES_USER: backlog_user
      POSTGRES_PASSWORD: backlogpassword123
      POSTGRES_DB: backlog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: backlog-redis
    ports:
      - "6379:6379"

  user-service:
    build: ./services/user-service
    container_name: backlog-user-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: backlog_db
      POSTGRES_USER: backlog_user
      POSTGRES_PASSWORD: backlogpassword123
      JWT_SECRET: changethislater
    depends_on:
      - postgres
      - redis

  backlog-service:
    build: ./services/backlog-service
    container_name: backlog-backlog-service
    ports:
      - "8002:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: backlog_db
      POSTGRES_USER: backlog_user
      POSTGRES_PASSWORD: backlogpassword123
      JWT_SECRET: changethislater
    depends_on:
      - postgres
      - redis
  integration-service:
    build: ./services/integration-service
    container_name: backlog-integration-service
    ports:
      - "8003:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: backlog_db
      POSTGRES_USER: backlog_user
      POSTGRES_PASSWORD: backlogpassword123
      JWT_SECRET: changethislater
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data: